/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppContentWrapper {
        "toggle": () => Promise<void>;
    }
    interface AppMain {
    }
}
declare global {
    interface HTMLAppContentWrapperElement extends Components.AppContentWrapper, HTMLStencilElement {
    }
    var HTMLAppContentWrapperElement: {
        prototype: HTMLAppContentWrapperElement;
        new (): HTMLAppContentWrapperElement;
    };
    interface HTMLAppMainElement extends Components.AppMain, HTMLStencilElement {
    }
    var HTMLAppMainElement: {
        prototype: HTMLAppMainElement;
        new (): HTMLAppMainElement;
    };
    interface HTMLElementTagNameMap {
        "app-content-wrapper": HTMLAppContentWrapperElement;
        "app-main": HTMLAppMainElement;
    }
}
declare namespace LocalJSX {
    interface AppContentWrapper {
    }
    interface AppMain {
    }
    interface IntrinsicElements {
        "app-content-wrapper": AppContentWrapper;
        "app-main": AppMain;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-content-wrapper": LocalJSX.AppContentWrapper & JSXBase.HTMLAttributes<HTMLAppContentWrapperElement>;
            "app-main": LocalJSX.AppMain & JSXBase.HTMLAttributes<HTMLAppMainElement>;
        }
    }
}
